lattice:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    cfg_file: examples/output/<EXP>.yaml
    run_for_epochs: 20
    eval_metrics: bleu
  train: !TrainingRegimen
    batcher: !SrcBatcher
      batch_size: 1
    glob:
      dropout: 0.5
      default_layer_dim: 128
    restart_trainer: True
    trainer: !AdamTrainer
      alpha: 0.0002
    lr_decay: 0.5
    dev_metrics: bleu
    corpus_parser: !BilingualCorpusParser
      src_reader: !LatticeTextReader
        use_words: False
        use_chars: True
        use_pronun_from: ~ #examples/mini-dict.en
      trg_reader: !PlainTextReader {}
      training_corpus: !BilingualTrainingCorpus
        train_src: examples/data/train.en
        train_trg: examples/data/train.ja
        dev_src: examples/data/dev.en
        dev_trg: examples/data/dev.ja
    model: !DefaultTranslator
      src_embedder: !LatticeEmbedder {}
      encoder: !BiLatticeLSTMTransducer
        layers: 3
      attender: !MlpAttender {}
      trg_embedder: !SimpleWordEmbedder {}
      decoder: !MlpSoftmaxDecoder
        layers: 1
        bridge: !CopyBridge {}
  decode: !XnmtDecoder
    src_file: examples/data/test.en
  evaluate:
    ref_file: examples/data/test.ja
