speech-self-att: !Experiment
  xnmt_global: !XnmtGlobal
    model_file: examples/output/{EXP}.mod
    out_file: examples/output/{EXP}.out
    err_file: examples/output/{EXP}.err
    dropout: 0.5
  model: !DefaultTranslator
    src_reader: !ContVecReader
      transpose: True
    trg_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: examples/data/head.en.vocab}
    src_embedder: !NoopEmbedder
      emb_dim: 240
    encoder: !ModularSeqTransducer
      modules:
      - !TransformerSeqTransducer
        layers: 2
        input_dim: 240
        hidden_dim: 512
        ff_hidden_dim: 512
        downsample_factor: 2
        diagonal_mask_width: ~
        mask_self: True
        ignore_masks: False
        plot_attention: ~ #examples/output/{EXP}.self-att
        positional_encoding_concat: 10
        diag_gauss_mask: rand
        downsampling_method: reshape
      - !BiLSTMSeqTransducer
        layers: 1
    attender: !MlpAttender
      state_dim: 64
      hidden_dim: 64
      input_dim: 512
    trg_embedder: !SimpleWordEmbedder
      emb_dim: 64
    decoder: !MlpSoftmaxDecoder
      layers: 1
      input_dim: 512
      mlp_hidden_dim: 64
      bridge: !NoBridge {}
  train: !SimpleTrainingRegimen
    src_file: examples/data/synth.contvec.npz
    trg_file: examples/data/synth.char
    run_for_epochs: 20
    batcher: !SrcBatcher
      batch_size: 3
      pad_src_to_multiple: 4
      src_pad_token: ~
    dev_tasks:
      - !LossEvalTask
        src_file: examples/data/synth.contvec.npz
        ref_file: examples/data/synth.char
    dev_tasks:
      - !LossEvalTask
        src_file: examples/data/synth.contvec.npz
        ref_file: examples/data/synth.char
      - !AccuracyEvalTask
        eval_metrics: cer,wer
        src_file: examples/data/synth.contvec.npz
        ref_file: examples/data/synth.char
        hyp_file: examples/output/{EXP}.dev_hyp
        inference: !SimpleInference
          post_process: join-char
  evaluate:
    - !AccuracyEvalTask
      eval_metrics: cer,wer
      src_file: examples/data/synth.contvec.npz
      ref_file: examples/data/synth.words
      hyp_file: examples/output/{EXP}.test_hyp
      inference: !SimpleInference
        post_process: join-char
