# This config file replicates the Listen-Attend-Spell architecture: https://arxiv.org/pdf/1508.01211.pdf
# Compared to the conventional attentional model, we remove input embeddings, instead directly read in a feature vector
# the pyramidal LSTM reduces length of the input sequence by a factor of 2 per layer (except for the first layer).
# Output units should be characters according to the paper.
speech-2layers:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    eval_metrics: cer,wer
    save_num_checkpoints: 2
  train: !SimpleTrainingRegimen
    run_for_epochs: 5
    src_format: contvec
    batcher: !SrcBatcher
      pad_to_multiple: 4
      batch_size: 3
    trainer: !AdamTrainer {}
    dev_metrics: wer
    glob:
      default_layer_dim: 32
      dropout: 0.4
    corpus_parser: !BilingualCorpusParser
      src_reader: !ContVecReader
        transpose: True
      trg_reader: !PlainTextReader {}
      training_corpus: !BilingualTrainingCorpus
        train_src: examples/data/synth.contvec.npz
        train_trg: examples/data/synth.char
        dev_src: examples/data/synth.contvec.npz
        dev_trg: examples/data/synth.char
    model: !DefaultTranslator
      src_embedder: !NoopEmbedder
        emb_dim: 240
      encoder: !PyramidalLSTMSeqTransducer
        layers: 3
        downsampling_method: concat
        reduce_factor: 2
        input_dim: 240
        hidden_dim: 64
      attender: !MlpAttender
        state_dim: 64
        hidden_dim: 64
        input_dim: 64
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 64
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 64
        bridge: !CopyBridge {}
  inference: !SimpleInference
    src_file: examples/data/synth.contvec.npz
  evaluate:
    ref_file: examples/data/synth.char
