speech-full:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: cer,wer
  train: !SimpleTrainingRegimen
    src_format: contvec
    batcher: !SrcBatcher
      pad_to_multiple: 4
      batch_size: 3
    trainer: !AdamTrainer {}
    glob:
      dropout: 0.5
    corpus_parser: !BilingualCorpusParser
      src_reader: !ContVecReader
        transpose: True
      trg_reader: !PlainTextReader {}
      training_corpus: !BilingualTrainingCorpus
        train_src: examples/data/synth.contvec.npz
        train_trg: examples/data/synth.char
        dev_src: examples/data/synth.contvec.npz
        dev_trg: examples/data/synth.char
    model: !DefaultTranslator
      sched_samp_max: 0.4
      sched_samp_epoch: 10
      src_embedder: !NoopEmbedder
        emb_dim: 240
      encoder: !PyramidalLSTMSeqTransducer
        layers: 3
        downsampling_method: concat
        reduce_factor: 2
        input_dim: 240
        hidden_dim: 64
      attender: !MultiHeadMlpAttender
        state_dim: 64
        hidden_dim: 64
        input_dim: 64
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 64
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 64
        input_dim: 64
        bridge: !NoBridge {}
        label_smoothing: 0.1
  decode: !XnmtDecoder
    src_file: examples/data/synth.contvec.npz
  evaluate:
    ref_file: examples/data/synth.char
