defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: bleu
  train:
    default_layer_dim: 512
    restart_trainer: True
    trainer: AIAYNAdam
    learning_rate: 1.0
    lr_decay: 1.0
    warmup_steps: 4000
    dev_metrics: bleu
    training_corpus: !BilingualTrainingCorpus
      train_src: examples/data/train.ja
      train_trg: examples/data/train.en
      dev_src: examples/data/dev.ja
      dev_trg: examples/data/dev.en
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !PlainTextReader {}
    model: !TransformerTranslator
      src_embedder: !SimpleWordEmbedder
        emb_dim: 512
      encoder: !TransformerEncoder
        layers: 1
      attender: !TransformerAttender
        hidden_dim: 512
        state_dim: 512
        input_dim: 512
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 512
      decoder: !TransformerDecoder
        layers: 1
        mlp_hidden_dim: 512
        bridge: !NoBridge {}
  decode:
    src_file: examples/data/test.ja
  evaluate:
    ref_file: examples/data/test.en

standard-dropout0.5:
  train:
    dropout: 0.5
